apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: yassineouhadi/eldycare-discovery-service:latest
          ports:
            - containerPort: 8761
          env:
          - name: container_discovery
            value: "discovery-service"