spring:
  application:
    name: authentication-service

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${random.value}

amqp:
  auth:
    queue: auth-queue
    exchange: auth-exchange
  user:
    queue: user-queue
    exchange: user-exchange
