
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j-service
  template:
    metadata:
      labels:
        app: neo4j-service
    spec:
      containers:
        - name: neo4j-service
          image: neo4j:latest
          ports:
            - containerPort: 7474
            - containerPort: 7687
          env:
            - name: NEO4J_AUTH
              value: neo4j/saga-pablo-lagoon-java-license-4169