apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres-service
  ports:
    - name: postgres-port
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer