apiVersion: v1
kind: Service
metadata:
  name: mongodb-reminder-service
spec:
  selector:
    app: mongodb-reminder-service
  ports:
    - name: mongodb-reminder-port
      protocol: TCP
      port: 27018
      targetPort: 27017
  type: LoadBalancer