apiVersion: v1
kind: Service
metadata:
  name: mongodb-notification-service
spec:
  selector:
    app: mongodb-notification-service
  ports:
    - name: mongodb-notification-port
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: LoadBalancer