server:
  port: 8888

ribbon:
  eureka:
   enabled: false

authentication-service:
  ribbon:
    listOfServers: http://authentication-service

AUTHENTICATION-SERVICE:
  ribbon:
    listOfServers: http://authentication-service
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

amqp:
  auth:
    queue: auth-queue
    exchange: auth-exchange

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      discovery:
        enabled: true
  application:
    name: gateway-service