name: eldycare backend CICD

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: "backend/**"
  pull_request:
    branches: ["main"]
    paths: "backend/**"

jobs:
  build-microservices:
    name: Build Microservices
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Microservices
        run: mvn -DskipTests clean install
        working-directory: ./backend

      - name: Upload Artifacts for discovery-service
        uses: actions/upload-artifact@v4.0.0
        with:
          name: discovery-service
          path: ./backend/discovery-service

  push-to-dockerhub-discovery-service:
    name: Push to Docker Hub - Discovery Service
    runs-on: ubuntu-latest
    needs: build-microservices
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: discovery-service
      - name: List Contents of Folders
        run: ls -R
      - name: Build & Push Docker Image - Discovery Service
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: yassineouhadi/eldycare-discovery-service
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  push-to-dockerhub-rabbitmq:
    name: Push to Docker Hub - RabbitMQ
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push RabbitMQ Docker Image
        run: docker-compose -f backend/docker-compose.yml build rabbitmq && docker-compose -f backend/docker-compose.yml push rabbitmq

  deploy-to-eks:
    name: Deploy to Amazon EKS
    runs-on: ubuntu-latest
    needs: push-to-dockerhub-discovery-service
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Check if EKS cluster exists
        run: |
          eks_cluster_name="eldycare-cluster"
          if aws eks describe-cluster --region us-east-1 --name $eks_cluster_name 2>/dev/null; then
            echo "EKS cluster $eks_cluster_name already exists."
          else
            echo "EKS cluster $eks_cluster_name does not exist. Creating..."
            cd backend
            terraform init
            terraform apply -auto-approve
            cd ..
          fi

      - name: Configure kubectl for EKS
        run: aws eks --region us-east-1 update-kubeconfig --name eldycare-cluster

      - name: Deploy Services to EKS
        run: |
          cd backend

          kubectl apply -f discovery-service/discovery-service-deployment.yaml
          kubectl apply -f discovery-service/discovery-service-service.yaml

          kubectl apply -f rabbitmq/rabbitmq-deployment.yaml
          kubectl apply -f rabbitmq/rabbitmq-service.yaml
